
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerjavahelloworldapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dockerjavahelloworldapp
  template:
    metadata:
      labels:
        app: dockerjavahelloworldapp
    spec:
      containers:
      - name: dockerjavahelloworldapp
        image: devopsdockercontainerregistry.azurecr.io/docker-java-hello-world-app:v2
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: dockerjavahelloworldapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: dockerjavahelloworldapp
